=== OlgaKhytriak/Hometasks/hometask12/src/MySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MySchema" xmlns:tns="http://www.example.org/MySchema" elementFormDefault="qualified">



    <element name="rate" type="tns:rate"></element>
    
    <complexType name="rate">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="providerName" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="subscriptionFee" type="double" maxOccurs="1" minOccurs="1"></element>
    		<element name="gigabytePrices" type="tns:elementPriceType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		<element name="videotecaFilmPrice" type="double" maxOccurs="1" minOccurs="1"></element>
    		<element name="parameters" type="tns:elementParameterType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="elementPriceType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="price" type="double"></element>
    	</sequence>
    	<attribute name="id" type="int"></attribute>
    </complexType>

    <complexType name="elementParameterType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="price" type="double"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>
</schema>

=== OlgaKhytriak/Hometasks/hometask12/src/MySchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:rate xmlns:tns="http://www.example.org/MySchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/MySchema MySchema.xsd ">
  <tns:name>Tariff</tns:name>
  <tns:providerName>Kyivstar</tns:providerName>
  <tns:subscriptionFee>333</tns:subscriptionFee>
  <tns:gigabytePrices id="0">
    <tns:name>tns:name</tns:name>
    <tns:price>0.0</tns:price>
  </tns:gigabytePrices>
  <tns:videotecaFilmPrice>0.0</tns:videotecaFilmPrice>
  <tns:parameters id="1">
    <tns:name>additionalSpeed</tns:name>
    <tns:price>11</tns:price>
  </tns:parameters>
  <tns:parameters>
  	<tns:name>tns:name</tns:name>
  	<tns:price>0.0</tns:price>
  </tns:parameters>
</tns:rate>
